export default {
  example: {
    index: '',
  },
  auth: {
    getOtp: '/auth/otp',
    checkOtp: '/auth/otp/check',
    checkToken: '/auth/user',
    loginAdmin: '/auth/login/admin',
    logout: '/auth/logout',
    registerPasien: '/auth/register',
    editProfile: '/auth/profile',
    getQrCodePasien: '/auth/qrcode',
    scanQrCodePasien: '/auth/qrcode/scan',
  },
  location: {
    province: '/location/province',
    regency: '/location/regency',
    district: '/location/district',
    village: '/location/village',
  },
  pemeriksaan: {
    poliklinik: '/poli',
    dokter: '/dokter',
    pendaftaran: '/pemeriksaan',
    riwayat: '/pemeriksaan/user',
    ttv: '/pemeriksaan/ttv',
    hapus: '/pemeriksaan/cancel',
    update: '/pemeriksaan/update',
    dokterByRs: '/dokter/by_rs',
    mulaiTtv: '/pemeriksaan/schedule/start_ttv',
    selesaiTtv: '/pemeriksaan/schedule/stop_ttv',
    mulaiPoli: '/pemeriksaan/schedule/start_poli',
    rumahSakit: '/rumah_sakit',
    verifikasi: '/pemeriksaan/verifikasi',
  },
  laboratorium: {
    laboratorium: '/laboratorium',
    orderLaboratorium: '/pemeriksaan/laboratorium',
    lastOrderLab: '/pemeriksaan/laboratorium/user/last',
    updateOrderLab: '/pemeriksaan/laboratorium/update',
    dokterLab: '/dokter_laboratorium/by_rs',
  },
  radiologi: {
    radiologi: '/radiologi',
    orderRadiologi: '/pemeriksaan/radiologi',
    lastOrderRadilogi: '/pemeriksaan/radiologi/user/last',
    updateOrderRadiologi: '/pemeriksaan/radiologi/update',
  },
}
